name: 'README Stats'
description: 'Updates stats in a README file.'
author: shawntoffel
inputs:
  github-token:
    description: 'The GitHub personal access token to use when fetching stats.'
    required: true
  github-user:
    description: 'The GitHub username for which stats will be pulled.'
    required: true
  file:
    description: 'The file where stats will be written.'
    required: false
    default: "README"
  exclude:
    description: 'Regex pattern for repos to exclude from the contribution count.'
    required: false
    default: ""
  version:
    description: 'Version of the underlying githubstats docker image'
    required: false
    default: "0.0.2"
runs:
  using: "composite"
  steps:
    - name: Update GitHub stats
      run: docker run -i ghcr.io/shawntoffel/githubstats:${{ inputs.version }} --token="${{ inputs.github-token }}" --login="${{ inputs.github-user }}" --exclude="${{ inputs.exclude }}" > "${{ github.workspace }}/${{ inputs.file }}"
      shell: sh
